grafana:
  enabled: true

  adminUser: admin
  adminPassword: Admin@123

  service:
    type: ClusterIP

  persistence:
    enabled: true
    storageClassName: ebs-gp3
    accessModes:
      - ReadWriteOnce
    size: 5Gi

  defaultDashboardsEnabled: true
  defaultDashboardsEditable: true


prometheus:
  enabled: true

  prometheusSpec:
    retention: 7d

    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: ebs-gp3
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi

    resources:
      requests:
        cpu: 250m
        memory: 512Mi
      limits:
        cpu: 1
        memory: 1Gi


alertmanager:
  enabled: true

nodeExporter:
  enabled: true

kubeStateMetrics:
  enabled: true

prometheusOperator:
  enabled: true
