apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: monitoring
  namespace: argo

spec:
  project: default

  sources:

    # Helm chart
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 77.5.0

      helm:
        valueFiles:
          - $values/monitoring/monitoring-values.yaml

    # GitHub repository containing values.yaml
    - repoURL: https://github.com//https:/radharamana10/github.com/radharamana10/k8s-test.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
